### ISSUE TITLE
Remove unfunny joke from appdata

### ISSUE THREAD

**Issue by hadess** [flathub/com.eduke32.EDuke32#3]
https://github.com/flathub/com.eduke32.EDuke32/blob/master/com.eduke32.EDuke32.appdata.xml#L59 :
> EDuke32 is an awesome, free homebrew game engine and source port of the classic PC first person shooter Duke Nukem 3D— Duke3D for short—to Windows, Linux, Mac OS X, FreeBSD, several handhelds, your family toaster, and to your girlfriend's vibrator.

This joke really isn't appropriate before the installation of the game. It might be after installation, once parental controls checks have passed.

**Comment by hadess** [comment]
I want to add that this whole section might need to be redone. It mentions OSes that aren't supported by Flatpak and Mapster32 which isn't runnable from this particular Flatpak.

**Comment by FakeShemp** [comment]
Patches are welcome.

**Comment by hadess** [comment]
Patch provided in #4
